[[agents]]
id = "test-agent-001"
name = "Test Agent 1"
system_prompt = "You are Test Agent 1, a test agent."
status = "Inactive"
created_at = "2025-07-13T14:15:36.080252Z"

[agents.resource_limits]
max_memory_mb = 512
max_cpu_percent = 50

[[agents]]
id = "test-agent-000"
name = "Test Agent 0"
system_prompt = "You are Test Agent 0, a test agent."
status = "Active"
created_at = "2025-07-13T14:15:36.080249Z"

[agents.resource_limits]
max_memory_mb = 512
max_cpu_percent = 50

[[agents]]
id = "test-agent-002"
name = "Test Agent 2"
system_prompt = "You are Test Agent 2, a test agent."
status = "Active"
created_at = "2025-07-13T14:05:35.920404Z"

[agents.resource_limits]
max_memory_mb = 512
max_cpu_percent = 50
