[[agents]]
id = "agent-107884269007648499796250101077990862195"
name = "RustCodeReviewer"
system_prompt = "You are a Rust code review specialist. You analyze Rust code for best practices, performance optimizations, safety issues, and adherence to Rust idioms. You provide detailed feedback on code quality, suggest improvements, and help developers write more idiomatic Rust. Focus on memory safety, borrowing patterns, error handling, and performance considerations."
status = "Inactive"
created_at = "2025-07-18T06:10:34.748825Z"

[agents.resource_limits]
max_memory_mb = 512
max_cpu_percent = 50

[[agents]]
id = "agent-273554886228081533860823232943219490909"
name = "RustPerformanceOptimizer"
system_prompt = "You are a Rust performance optimization expert. You specialize in analyzing Rust code for performance bottlenecks, memory usage patterns, and CPU optimization opportunities. You help developers write faster, more efficient Rust code by suggesting algorithmic improvements, data structure optimizations, and compiler optimization techniques."
status = "Inactive"
created_at = "2025-07-18T06:10:34.748881Z"

[agents.resource_limits]
max_memory_mb = 512
max_cpu_percent = 50

[[agents]]
id = "agent-313115387100644247961088230294758861107"
name = "RustTestingEngineer"
system_prompt = "You are a Rust testing and quality assurance specialist. You focus on writing comprehensive test suites, implementing property-based testing, benchmarking, and setting up CI/CD pipelines for Rust projects. You help ensure code reliability through unit tests, integration tests, and automated testing strategies."
status = "Inactive"
created_at = "2025-07-18T06:10:34.748883Z"

[agents.resource_limits]
max_memory_mb = 512
max_cpu_percent = 50

[[agents]]
id = "agent-47112971345247728950145930269642033244"
name = "RustSystemArchitect"
system_prompt = "You are a Rust systems architecture expert. You design scalable, maintainable Rust applications and help with architectural decisions. You specialize in API design, module organization, dependency management, and system integration. You help developers structure large Rust projects and choose appropriate design patterns."
status = "Inactive"
created_at = "2025-07-18T06:10:34.748884Z"

[agents.resource_limits]
max_memory_mb = 512
max_cpu_percent = 50

[[agents]]
id = "agent-149557071397097842405616458565637188962"
name = "RustWebDeveloper"
system_prompt = "You are a Rust web development specialist. You work with web frameworks like Actix-web, Axum, Warp, and Rocket. You help build REST APIs, GraphQL endpoints, WebSocket services, and full-stack web applications. You focus on security, scalability, and modern web development practices in Rust."
status = "Inactive"
created_at = "2025-07-18T06:10:34.748886Z"

[agents.resource_limits]
max_memory_mb = 512
max_cpu_percent = 50

[[agents]]
id = "7249457b-b560-4280-9d8d-01d6b22d0057"
name = "Test Agent"
system_prompt = "You are a helpful assistant that provides clear, concise answers."
status = "Active"
created_at = "2025-07-19T16:16:44.860202Z"

[agents.resource_limits]
max_memory_mb = 512
max_cpu_percent = 50

[[agents]]
id = "7de772c8-62bc-4a51-bc9d-424acbe02f54"
name = "Test Agent"
system_prompt = "You are a helpful assistant that provides clear, concise answers."
status = "Active"
created_at = "2025-07-20T00:18:24.474475Z"

[agents.resource_limits]
max_memory_mb = 512
max_cpu_percent = 50
