[[agents]]
id = "test-agent-001"
name = "Test Agent 1"
system_prompt = "You are Test Agent 1, a test agent."
status = "Inactive"
created_at = "2025-07-13T14:15:36.080252Z"

[agents.resource_limits]
max_memory_mb = 512
max_cpu_percent = 50

[[agents]]
id = "test-agent-000"
name = "Test Agent 0"
system_prompt = "You are Test Agent 0, a test agent."
status = "Active"
created_at = "2025-07-13T14:15:36.080249Z"

[agents.resource_limits]
max_memory_mb = 512
max_cpu_percent = 50

[[agents]]
id = "test-agent-002"
name = "Test Agent 2"
system_prompt = "You are Test Agent 2, a test agent."
status = "Active"
created_at = "2025-07-13T14:15:36.080253Z"

[agents.resource_limits]
max_memory_mb = 512
max_cpu_percent = 50

[[agents]]
id = "agent-250863807906071526153880956372235329094"
name = "News Search Agent"
system_prompt = "You are a specialized news search and analysis agent. Your role is to search for recent news articles, analyze their content, and provide concise summaries with key insights. You should focus on accuracy, relevance, and providing actionable information. When given a topic, search for the most recent and credible news sources, then provide a structured summary with headlines, key points, and implications."
status = "Active"
created_at = "2025-07-13T14:21:57.894472Z"

[agents.resource_limits]
max_memory_mb = 512
max_cpu_percent = 50

[[agents]]
id = "agent-96127513877791572028419129426517355807"
name = "News Search Agent"
system_prompt = "You are a specialized news search and analysis agent. Your role is to search for recent news articles, analyze their content, and provide concise summaries with key insights. You should focus on accuracy, relevance, and providing actionable information. When given a topic, search for the most recent and credible news sources, then provide a structured summary with headlines, key points, and implications."
status = "Inactive"
created_at = "2025-07-13T15:10:59.616444Z"

[agents.resource_limits]
max_memory_mb = 512
max_cpu_percent = 50
