[[agents]]
id = "test-agent-001"
name = "Test Agent"
system_prompt = "You are a helpful test agent."
status = "Inactive"
created_at = "2025-07-13T13:33:32.475483Z"

[agents.resource_limits]
max_memory_mb = 512
max_cpu_percent = 50
